Document: h2osteam
Title: Debian h2osteam Manual
Author: <insert document author here>
Abstract: This manual describes what h2osteam is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/h2osteam/h2osteam.sgml.gz

Format: postscript
Files: /usr/share/doc/h2osteam/h2osteam.ps.gz

Format: text
Files: /usr/share/doc/h2osteam/h2osteam.text.gz

Format: HTML
Index: /usr/share/doc/h2osteam/html/index.html
Files: /usr/share/doc/h2osteam/html/*.html
